/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.AdminController;
import java.util.List;
import javax.swing.JOptionPane;
import Model.Bean.CBBItem;
import java.awt.Frame;

/**
 *
 */
public class AddProduct extends javax.swing.JDialog {

    /**
     * Creates new form ThemSP
     */
    AdminController adminController;
    
    public AddProduct(Frame jf, boolean modal) {
        super(jf, modal);
        initComponents();
    }
    
    public AddProduct(Frame jf, boolean modal, AdminController ad, List<CBBItem> list) {
        super(jf, modal);
        this.adminController = ad;
        initComponents();
        setLocationRelativeTo(null);
        setCombobox(list);
    }

    void setCombobox(List<CBBItem> list) {
        for (CBBItem item : list) {
            cbbmaNCC.addItem(item);
        }
        cbbmaNCC.setSelectedItem(list.get(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbmamay = new javax.swing.JLabel();
        txtmamay = new javax.swing.JTextField();
        lbmanhacungcap = new javax.swing.JLabel();
        cbbmaNCC = new javax.swing.JComboBox<>();
        lbgia = new javax.swing.JLabel();
        txtgia = new javax.swing.JTextField();
        lbtenmay = new javax.swing.JLabel();
        txttenmay = new javax.swing.JTextField();
        lbsoluong = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        lbloaimay = new javax.swing.JLabel();
        txtloaimay = new javax.swing.JTextField();
        lbkichthuoc = new javax.swing.JLabel();
        txtkichthuoc = new javax.swing.JTextField();
        lbxuatxu = new javax.swing.JLabel();
        txtxuatxu = new javax.swing.JTextField();
        lbdungluongpin = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtDungLuongPin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm sản phẩm mới");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbmamay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbmamay.setText("Product code:");

        txtmamay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtmamay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbmanhacungcap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbmanhacungcap.setText("Supplier:");

        cbbmaNCC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cbbmaNCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbgia.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbgia.setText("Unit price:");

        txtgia.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtgia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbtenmay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbtenmay.setText("Product name:");

        txttenmay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txttenmay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbsoluong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbsoluong.setText("Quantity:");

        txtsoluong.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtsoluong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbloaimay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbloaimay.setText("Type:");

        txtloaimay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtloaimay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtloaimay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloaimayActionPerformed(evt);
            }
        });

        lbkichthuoc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbkichthuoc.setText("Screen size");

        txtkichthuoc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtkichthuoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbxuatxu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbxuatxu.setText("Origin:");

        txtxuatxu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtxuatxu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbdungluongpin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbdungluongpin.setText("Battery capacity:");

        btnAddProduct.setBackground(new java.awt.Color(54, 164, 255));
        btnAddProduct.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("Add");
        btnAddProduct.setBorder(null);
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(54, 164, 255));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtDungLuongPin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtDungLuongPin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbmamay)
                    .addComponent(txtmamay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbmanhacungcap)
                    .addComponent(cbbmaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbgia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttenmay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbsoluong)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbloaimay)
                            .addComponent(txtloaimay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtenmay))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDungLuongPin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbkichthuoc)
                            .addComponent(txtkichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbxuatxu)
                            .addComponent(lbdungluongpin))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbmamay)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtmamay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lbmanhacungcap)
                            .addGap(8, 8, 8)
                            .addComponent(cbbmaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lbgia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbtenmay)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txttenmay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lbsoluong)
                            .addGap(8, 8, 8)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lbloaimay)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtloaimay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbkichthuoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtkichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbxuatxu)
                        .addGap(8, 8, 8)
                        .addComponent(txtxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbdungluongpin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDungLuongPin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 400));

        jPanel2.setBackground(new java.awt.Color(58, 62, 71));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD NEW PRODUCT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel1)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:

        try {
            if (txtmamay.getText().isEmpty() 
                    || txttenmay.getText().isEmpty() 
                    || txtxuatxu.getText().isEmpty()
                    || txtgia.getText().isEmpty() 
                    || txtDungLuongPin.getText().isEmpty() 
                    || txtkichthuoc.getText().isEmpty()
                    || txtloaimay.getText().isEmpty() 
                    || txtsoluong.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter all the required information!");
                return;
            }
            String maNhaCungCap = ((CBBItem) cbbmaNCC.getSelectedItem()).getValue();
            if (maNhaCungCap == null || maNhaCungCap.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please select a supplier code!");
                return;
            }
            int soluong = Integer.parseInt(txtsoluong.getText());
            float gia = Float.parseFloat(txtgia.getText());
            float kichthuoc = Float.parseFloat(txtkichthuoc.getText());

            adminController.sendMessage("addProduct;" + txtmamay.getText() + "," + maNhaCungCap + ","
                        + txttenmay.getText() + "," + soluong + "," + gia + ","
                        + txtloaimay.getText() + "," + kichthuoc + "," + txtDungLuongPin.getText()
                        + "," + txtxuatxu.getText());
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric value!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtloaimayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloaimayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloaimayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddProduct dialog = new AddProduct(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<CBBItem> cbbmaNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbdungluongpin;
    private javax.swing.JLabel lbgia;
    private javax.swing.JLabel lbkichthuoc;
    private javax.swing.JLabel lbloaimay;
    private javax.swing.JLabel lbmamay;
    private javax.swing.JLabel lbmanhacungcap;
    private javax.swing.JLabel lbsoluong;
    private javax.swing.JLabel lbtenmay;
    private javax.swing.JLabel lbxuatxu;
    private javax.swing.JTextField txtDungLuongPin;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtkichthuoc;
    private javax.swing.JTextField txtloaimay;
    private javax.swing.JTextField txtmamay;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenmay;
    private javax.swing.JTextField txtxuatxu;
    // End of variables declaration//GEN-END:variables
}
