/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.AdminController;
import Model.Bean.CBBItem;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import Model.Bean.MayTinh;
import java.awt.Frame;
import javax.swing.JTextField;

public class UpdateProduct extends javax.swing.JDialog {

    /**
     * Creates new form ThemSP
     */
    AdminController adminController;

    public UpdateProduct(Frame jf, boolean modal) {
        super(jf, modal);
        initComponents();
    }

    public UpdateProduct(Frame jf, boolean modal, AdminController ad, List<CBBItem> list, MayTinh may) {
        super(jf, modal);
        this.adminController = ad;
        initComponents();
        setLocationRelativeTo(null);
        setCombobox(list);
        displayInfo(may);
    }

    void setCombobox(List<CBBItem> list) {
        for (CBBItem item : list) {
            cbbmaNCC.addItem(item);
        }
    }

    CBBItem getSelectedCBBItem(String ma) {
        for (int i = 0; i < cbbmaNCC.getItemCount(); i++) {
            CBBItem item = (CBBItem) cbbmaNCC.getItemAt(i);
            if (item.getValue().equals(ma)) {
                return item;
            }
        }
        return null;
    }

    // Phương thức để set giá trị float vào JTextField
    private static void setFloatValue(JTextField textField, float value) {
        // Định dạng số để chuyển đổi giá trị float thành chuỗi
        DecimalFormat decimalFormat = new DecimalFormat("#.#####");
        textField.setText(decimalFormat.format(value));
    }

    private void displayInfo(MayTinh a) {
        txtmamay.setText(a.getmaMay());
        CBBItem item = getSelectedCBBItem(a.getmaNhaCungCap());
        if (item != null) {
            cbbmaNCC.setSelectedItem(item);
        }
        txtsoluong.setText(String.valueOf(a.getsoluong()));
        setFloatValue(txtgia, a.getgia());
        txttenmay.setText(a.gettenmay());
        txtxuatxu.setText(a.getxuatxu());
        txtloaimay.setText(a.getloaimay());
        txtkichthuoc.setText(String.valueOf(a.getkichthuoc()));
        txtDungLuongPin.setText(String.valueOf(a.getdungluongpin()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbmamay = new javax.swing.JLabel();
        lbmaNCC = new javax.swing.JLabel();
        lbsoluong = new javax.swing.JLabel();
        txttenmay = new javax.swing.JTextField();
        txtmamay = new javax.swing.JTextField();
        lbloaimay = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lbxuatxu = new javax.swing.JLabel();
        txtxuatxu = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        lbgia = new javax.swing.JLabel();
        cbbmaNCC = new javax.swing.JComboBox<>();
        lbtenmay = new javax.swing.JLabel();
        txtgia = new javax.swing.JTextField();
        txtloaimay = new javax.swing.JTextField();
        txtkichthuoc = new javax.swing.JTextField();
        txtDungLuongPin = new javax.swing.JTextField();
        lbdungluong = new javax.swing.JLabel();
        lbkichthuoc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chỉnh sửa sản phẩm");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbmamay.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        lbmamay.setText("Product code:");

        lbmaNCC.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        lbmaNCC.setText("Supplier:");

        lbsoluong.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        lbsoluong.setText("Quantity:");

        txttenmay.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txttenmay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtmamay.setEditable(false);
        txtmamay.setBackground(new java.awt.Color(229, 230, 230));
        txtmamay.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtmamay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmamay.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        lbloaimay.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        lbloaimay.setText("Type:");

        btnAddProduct.setBackground(new java.awt.Color(54, 164, 255));
        btnAddProduct.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("Save");
        btnAddProduct.setBorder(null);
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(54, 164, 255));
        btnCancel.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lbxuatxu.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        lbxuatxu.setText("Origin:");

        txtxuatxu.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtxuatxu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtsoluong.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtsoluong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbgia.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        lbgia.setText("Unit price:");

        cbbmaNCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbtenmay.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        lbtenmay.setText("Product name:");

        txtgia.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtgia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtloaimay.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtloaimay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtkichthuoc.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtkichthuoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtDungLuongPin.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        txtDungLuongPin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbdungluong.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        lbdungluong.setText("Battery capacity:");

        lbkichthuoc.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        lbkichthuoc.setText("Screen size");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbmamay)
                            .addComponent(lbmaNCC)
                            .addComponent(cbbmaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmamay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbkichthuoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbgia)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtkichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbdungluong)
                                            .addComponent(txtDungLuongPin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbloaimay)
                            .addComponent(txtloaimay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtenmay)
                            .addComponent(txttenmay, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbxuatxu)
                            .addComponent(txtxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbmamay)
                    .addComponent(lbgia)
                    .addComponent(lbloaimay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmamay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtloaimay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbmaNCC)
                    .addComponent(lbkichthuoc)
                    .addComponent(lbtenmay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbmaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttenmay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsoluong)
                    .addComponent(lbdungluong)
                    .addComponent(lbxuatxu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDungLuongPin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 400));

        jPanel2.setBackground(new java.awt.Color(58, 62, 71));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE PRODUCT INFORMATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(300, 300, 300))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        try {
            if (txtmamay.getText().isEmpty() || txttenmay.getText().isEmpty() || txtxuatxu.getText().isEmpty()
                    || txtgia.getText().isEmpty() || txtDungLuongPin.getText().isEmpty() || txtkichthuoc.getText().isEmpty()
                    || txtloaimay.getText().isEmpty() || txtsoluong.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter all the required information!");
                return;
            }
            String maNhaCungCap = ((CBBItem) cbbmaNCC.getSelectedItem()).getValue();
            if (maNhaCungCap == null || maNhaCungCap.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please select a supplier!");
                return;
            }
            int soluong = Integer.parseInt(txtsoluong.getText());
            float gia = Float.parseFloat(txtgia.getText());
            float kichthuoc = Float.parseFloat(txtkichthuoc.getText());

            adminController.sendMessage("editProduct;" + txtmamay.getText() + "," + maNhaCungCap + ","
                    + txttenmay.getText() + "," + soluong + "," + gia + ","
                    + txtloaimay.getText() + "," + kichthuoc + "," + txtDungLuongPin.getText()
                    + "," + txtxuatxu.getText());
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric values!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        adminController.sendMessage("stopEditProduct;" + txtmamay.getText());
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        adminController.sendMessage("stopEditProduct;" + txtmamay.getText());
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            UpdateProduct dialog = new UpdateProduct(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<CBBItem> cbbmaNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbdungluong;
    private javax.swing.JLabel lbgia;
    private javax.swing.JLabel lbkichthuoc;
    private javax.swing.JLabel lbloaimay;
    private javax.swing.JLabel lbmaNCC;
    private javax.swing.JLabel lbmamay;
    private javax.swing.JLabel lbsoluong;
    private javax.swing.JLabel lbtenmay;
    private javax.swing.JLabel lbxuatxu;
    private javax.swing.JTextField txtDungLuongPin;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtkichthuoc;
    private javax.swing.JTextField txtloaimay;
    private javax.swing.JTextField txtmamay;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenmay;
    private javax.swing.JTextField txtxuatxu;
    // End of variables declaration//GEN-END:variables
}
